question_data = [
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "The two atomic bombs dropped on Japan by the United States in August 1945 were named 'Little Man' and 'Fat Boy'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Greenland is covered with grass and Iceland covered with ice.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean",
     "difficulty": "medium",
     "question": "Coca-Cola's original colour was green.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy", "question": "Luigi is taller than Mario?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean",
     "difficulty": "easy",
     "question": "RAM stands for Random Access Memory.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean",
     "difficulty": "easy",
     "question": "Ada Lovelace is often considered the first computer programmer.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "medium",
     "question": "According to Norse mythology, Loki is a mother.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean",
     "difficulty": "easy", "question": "The Sun rises from the North.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "medium",
     "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Comics", "type": "boolean",
     "difficulty": "medium",
     "question": "In the webcomic Homestuck, the first character introduced is Dave Strider.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean",
     "difficulty": "easy",
     "question": "The alternative rock band, They Might Be Giants, released their album 'Flood' in 1990. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean",
     "difficulty": "easy",
     "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "medium",
     "question": "The Platypus is a mammal.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean",
     "difficulty": "medium",
     "question": "&quot;Twenty One Pilots&quot; made the song &quot;The Motion&quot; featuring Sampha.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
     "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "Cats have whiskers under their legs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "Adolf Hitler was tried at the Nuremberg trials.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "Valve's &quot;Portal&quot; and &quot;Half-Life&quot; franchises exist within the same in-game universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean",
     "difficulty": "easy",
     "question": "Linux was first created as an alternative to Windows XP.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Celebrities", "type": "boolean", "difficulty": "hard",
     "question": "Lady Gaga's real name is Stefani Joanne Angelina Germanotta.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean",
     "difficulty": "hard",
     "question": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean",
     "difficulty": "medium",
     "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Politics", "type": "boolean", "difficulty": "easy",
     "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "The United States of America was the first country to launch a man into space.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean",
     "difficulty": "medium",
     "question": "Metallica collaborated with Rowan Atkinson's Mr Bean on a 1992 comic relief single.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "The internet browser Firefox is named after the Red Panda.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "Doki Doki Literature Club was developed in Japan.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean",
     "difficulty": "medium",
     "question": "The original ending of &quot;Little Shop Of Horrors&quot; has the plants taking over the world.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
